### PR TITLE
#160 merge fix

### LINKED ISSUE #160: (M)General issue found: Mobile app doesn't like sync out records when you have a sync out type = "M" which is merging
@edmofro : Feel free to close this once you have a answer to it.

I found this issue yesterday on demo EC2 server while trying to dump all the records in to the app.
There were some records in the sync out table some of it having a sync out type = M
When app tries to collect that data : Gave me an message saying : Cannot integrate with sync type m .

Taking this : We cannot ignore the fact that we can have some pre existing sync out records with this type - Any thoughts?

# Implementation notes
Handling merge on mobile to avoid server bombing mobile with sync records from a merge.
Server will have to handle the fact that mobile pushes sync changes to server before pulling. This means that mobile may push records referencing records that have been merged and deleted already on the server.
Handling merge on site means handling all these tables (feel free to correct!).
Architecture wise (pending more discussion), perhaps something similar to the delete record code - e.g. find all `Transactions` that have `TransactionBatches` referring to the item to delete in the merge and call `Transaction.mergeItems(itemA, itemB)`. A similar thing is done for all `TransactionBatches`; `TransactionBatch.mergeBatches`...

**All pending researching if realm has effective means of managing merging of records.**
If realm can smartly update all existing references to a item/name to point to another, then easy peasy.
### Names
Tables to update:
- [ ] Name 
- [ ] Transaction
- [ ] Requisition
- [ ] NameStoreJoin
- [ ] MasterListNameJoin
- [ ] Stocktake
### Items
Tables to update:
- [ ] Item 
- [ ] ItemBatch
- [ ] ItemStoreJoin
- [ ] MasterListItem
- [ ] Transaction
- [ ] TransactionItem
- [ ] TransactionBatch
- [ ] Requisition
- [ ] RequisitionItem
- [ ] Stocktake
- [ ] StocktakeItem
- [ ] StocktakeBatch

### PR DESCRIPTION
**Pull request by wlthomson**
Fixes #160.

Added logic for syncing merged items and names. Tested working with realm@1.13.0.

### CODE REVIEW

File: src/sync/incomingSyncUtils.js [hunk 1]
```diff
@@ -12,117 +12,244 @@ import {
...
-  const recordType = syncRecord.RecordType;
+export function integrateobject(database, settings, syncobject) {
+  // If the sync object is missing either data, object type, sync type, or object ID, ignore
+  if (!syncobject.objectType || !syncobject.SyncType) return;
+  const syncType = syncobject.SyncType;
+  const objectType = syncobject.objectType;
   const changeType = SYNC_TYPES.translate(syncType, EXTERNAL_TO_INTERNAL);
-  const internalRecordType = RECORD_TYPES.translate(recordType, EXTERNAL_TO_INTERNAL);
+  const internalobjectType = object_TYPES.translate(objectType, EXTERNAL_TO_INTERNAL);
+  if (changeType === 'merge') {
```
Comment (andreievg) [inline src/sync/incomingSyncUtils.js]: this can be in switch statement below

File: src/sync/incomingSyncUtils.js [hunk 2]
```diff
@@ -12,117 +12,244 @@ import {
...
+
+/**
+ * Merge two existing objects. Two-level lookup table for 1) the objects related to the type
+ * of the merging objects 2) the fields of the related object to update. Point related objects
+ * of the merged object to point to the kept object and delete.
+ * @param {Realm}  database    The local database
+ * @param {object} settings    Access to app settings
+ * @param {object} mergeobject Data representing the sync object
+ */
+export function mergeobjects(database, settings, mergeobject) {
```
[the remark this answers is not in the document]
Comment (andreievg) [reply src/sync/incomingSyncUtils.js]: Also camel case for parameter, `recordObject`

File: src/sync/incomingSyncUtils.js [hunk 3]
```diff
@@ -12,117 +12,244 @@ import {
...
+    },
+    name: {
+      ItemBatch: 'supplier',
+      Transaction: 'otherParty',
+      Requisition: 'otherStoreName',
+    },
+  };
+
+  const mergedObjectsInternalType = object_TYPES.translate(
+    mergeobject.objectType,
```
Comment (andreievg) [inline src/sync/incomingSyncUtils.js]: can pass this from `integrateRecord` method

File: src/sync/incomingSyncUtils.js [hunk 4]
```diff
@@ -12,117 +12,244 @@ import {
...
+/**
+ * Merge two existing objects. Two-level lookup table for 1) the objects related to the type
+ * of the merging objects 2) the fields of the related object to update. Point related objects
+ * of the merged object to point to the kept object and delete.
+ * @param {Realm}  database    The local database
+ * @param {object} settings    Access to app settings
+ * @param {object} mergeobject Data representing the sync object
+ */
+export function mergeobjects(database, settings, mergeobject) {
+  const object_TYPE_TO_TABLES = {
```
Comment (andreievg) [inline src/sync/incomingSyncUtils.js]: not a big fan of this naming. maybe `RECORD_SIMPLE_LINKING` ? not sure if i like that one either hehe

File: src/sync/incomingSyncUtils.js [hunk 5]
```diff
@@ -12,117 +12,244 @@ import {
...
+    .filtered('id == $0', mergeobject.mergeIDtodelete)[0];
+
+  if (!(objectToKeep && objectToMerge)) {
+    return;
+  }
+
+  const tablesToUpdate = object_TYPE_TO_TABLES[mergeobject.objectType];
+
+  if (tablesToUpdate) {
+    Object.keys(tablesToUpdate).forEach(tableToUpdate => {
```
Comment (andreievg) [inline src/sync/incomingSyncUtils.js]: `Object.entries(tablesToUpdate).forEach(([tableToUpdate, fieldToUpdate]) => ... )
I think it's a bit simpler

File: src/sync/incomingSyncUtils.js [hunk 6]
```diff
@@ -12,117 +12,244 @@ import {
...
+    .objects(mergedObjectsInternalType)
+    .filtered('id == $0', mergeobject.mergeIDtodelete)[0];
+
+  if (!(objectToKeep && objectToMerge)) {
+    return;
+  }
+
+  const tablesToUpdate = object_TYPE_TO_TABLES[mergeobject.objectType];
+
+  if (tablesToUpdate) {
```
Comment (andreievg) [inline src/sync/incomingSyncUtils.js]: To avoid further indentations, i would return from method if !tablesToUpdate. Can also add a todo comment if !tablesToUpdate (`// TODO log to bugsnag if merging not implemented for a certain recordType`)

File: src/sync/incomingSyncUtils.js [hunk 7]
```diff
@@ -12,117 +12,244 @@ import {
...
+    Object.keys(tablesToUpdate).forEach(tableToUpdate => {
+      const fieldToUpdate = tablesToUpdate[tableToUpdate];
+      const objectsToUpdate = database
+        .objects(tableToUpdate)
+        .filtered(`${fieldToUpdate}.id == $0`, objectToMerge.id)
+        .snapshot();
+      if (objectsToUpdate.length > 0) {
```
Comment (andreievg) [inline src/sync/incomingSyncUtils.js]: don't really need to check for, objectsToUpdate.length > 0, as forEach will not iterate if length > 0

File: src/sync/incomingSyncUtils.js [hunk 8]
```diff
@@ -12,117 +12,244 @@ import {
...
+        objectsToUpdate.forEach(object => {
+          if (object) {
+            // Explicitly set Transaction.otherParty
+            // TODO: replace with listener or setter on Transaction object
+            if (tableToUpdate === 'Transaction') {
+              object.setOtherParty(objectToKeep);
```
Comment (andreievg) [inline src/sync/incomingSyncUtils.js]: Hmm, `object_TYPE_TO_TABLES` can be like this:
```
Name: {
 Transaction: {
     field: 'otherParty',
     setterMethod: 'setOtherParty'
 },
}
```
then
```Object.entries(tablesToUpdate).forEach(([tableToUpdate, {field: fieldToUpdate, setterMethod: setterForField ]) => ... )```
then here, you can just do this:
```
if(setterForField) {
record[setterForField](recordTokeep)
} else {
 record[fieldToUpdate] = recordToKeep
}
```

File: src/sync/incomingSyncUtils.js [hunk 9]
```diff
@@ -12,117 +12,244 @@ import {
...
+            } else {
+              object[fieldToUpdate] = objectToKeep;
+              database.update(tableToUpdate, object);
```
Comment (andreievg) [inline src/sync/incomingSyncUtils.js]: don't need to call database.update -> it's only needed if you want the records to be synced to server (server does it's own merging)

**Comment by wlthomson** [comment]
Have added second lookup RECORD_TYPE_TO_MASTERLIST for master list logic. This simplifies the code in a similar manner to RECORD_TYPE_TO_TABLE does for the other tables.

File: src/sync/incomingSyncUtils.js (hunk 2 above)
[the remark this answers is not in the document]
Comment (wlthomson) [reply src/sync/incomingSyncUtils.js]: All relevant variables names containing object updated to use record naming scheme.

File: src/sync/incomingSyncUtils.js [hunk 10]
```diff
@@ -12,117 +12,244 @@ import {
...
+ * Merge two existing objects. Two-level lookup table for 1) the objects related to the type
+ * of the merging objects 2) the fields of the related object to update. Point related objects
+ * of the merged object to point to the kept object and delete.
+ * @param {Realm}  database    The local database
+ * @param {object} settings    Access to app settings
+ * @param {object} mergeobject Data representing the sync object
+ */
+export function mergeobjects(database, settings, mergeobject) {
+  const object_TYPE_TO_TABLES = {
+    item: {
```
[the remark this answers is not in the document]
Comment (wlthomson) [reply src/sync/incomingSyncUtils.js]: RECORD_TYPE_TO_TABLE updated to use internal naming.

File: src/sync/incomingSyncUtils.js (hunk 1 above)
Comment (wlthomson) [reply src/sync/incomingSyncUtils.js]: Logic for detection of merge sync record moved into relevant switch statement.

File: src/sync/incomingSyncUtils.js (hunk 3 above)
Comment (wlthomson) [reply src/sync/incomingSyncUtils.js]: EXTERNAL_TO_INTERNAL translation moved to integrateRecord and passed to mergeRecords as parameter.

File: src/sync/incomingSyncUtils.js (hunk 7 above)
Comment (wlthomson) [reply src/sync/incomingSyncUtils.js]: Remove unneeded length checking in forEach loop.

File: src/sync/incomingSyncUtils.js (hunk 6 above)
Comment (wlthomson) [reply src/sync/incomingSyncUtils.js]: Bugsnag TODO comment added when no tablesToUpdate.

File: src/sync/incomingSyncUtils.js [hunk 11]
```diff
@@ -43,11 +86,91 @@ export function integrateRecord(database, settings, syncRecord) {
...
+
+  Object.entries(tablesToUpdate).forEach(
+    ([tableToUpdate, { field: fieldToUpdate, setter: fieldSetter }]) => {
+      const recordsToUpdate = database
+        .objects(tableToUpdate)
+        .filtered(`${fieldToUpdate}.id == $0`, recordToMerge.id)
+        .snapshot();
+      recordsToUpdate.forEach(record => {
+        if (record) {
+          // TODO: automatically add Transaction to otherParty.transactions when Transaction.otherParty is set
```
Comment (andreievg) [inline src/sync/incomingSyncUtils.js]: I think this TODO has been fulfilled by setOtherParty on Transaction

File: src/sync/incomingSyncUtils.js [hunk 12]
```diff
@@ -43,11 +86,91 @@ export function integrateRecord(database, settings, syncRecord) {
...
+      });
+    },
+  );
+
+  const [[tableToUpdate, { field: fieldToUpdate }]] = Object.entries(
+    RECORD_TYPE_TO_MASTERLIST[internalRecordType],
+  );
+  const masterListRecord = database
+    .objects(masterListToUpdate)
+    .filtered(`${fieldToUpdate}.id == $0`, recordToMerge.id)[0];
```
Comment (andreievg) [inline src/sync/incomingSyncUtils.js]: Item/Name may belong to multiple master list, so should look through all master list with recordToMerge and recordToKeep.

File: src/database/DataTypes/Item.js [hunk 13]
```diff
@@ -5,6 +5,11 @@ const USAGE_PERIOD_MILLISECONDS = 3 * 30 * MILLISECONDS_PER_DAY; // Three months
 
 export class Item extends Realm.Object {
   destructor(database) {
+    // Clean up item store joins referencing deleted item.
+    const itemStoreJoins = database.objects('ItemStoreJoin').filtered('itemId == $0', this.id);
+    database.delete('ItemStoreJoin', itemStoreJoins);
+
+    this.batches = database.objects('ItemBatch').filtered('item.id == $0', this.id);
```
[the remark this answers is not in the document]
Comment (wlthomson) [reply src/database/DataTypes/Item.js]: Done!

File: src/sync/incomingSyncUtils.js (hunk 11 above)
Comment (joshxg) [reply src/sync/incomingSyncUtils.js]: Removed.

File: src/sync/incomingSyncUtils.js [hunk 14]
```diff
@@ -43,11 +86,91 @@ export function integrateRecord(database, settings, syncRecord) {
...
+    ([tableToUpdate, { field: fieldToUpdate, setter: fieldSetter }]) => {
+      const recordsToUpdate = database
+        .objects(tableToUpdate)
+        .filtered(`${fieldToUpdate}.id == $0`, recordToMerge.id)
+        .snapshot();
+      recordsToUpdate.forEach(record => {
+        if (record) {
+          // TODO: automatically add Transaction to otherParty.transactions when Transaction.otherParty is set
+          const setterMethod =
+            typeof record[fieldSetter] === typeof Function ? record[fieldSetter] : null;
```
[the remark this answers is not in the document]
Comment (joshxg) [reply src/sync/incomingSyncUtils.js]: Removed arbitrary setterMethod variable.

File: src/sync/incomingSyncUtils.js [hunk 15]
```diff
@@ -43,11 +86,91 @@ export function integrateRecord(database, settings, syncRecord) {
...
+  );
+  const masterListRecord = database
+    .objects(masterListToUpdate)
+    .filtered(`${fieldToUpdate}.id == $0`, recordToMerge.id)[0];
+  const duplicateMasterListRecord = database
+    .objects(masterListToUpdate)
+    .filtered(
+      `(${fieldToUpdate}.id == $0) && ('masterList.id == $0')`,
+      recordToKeep.id,
+      masterListRecord.masterList.id[0],
```
[the remark this answers is not in the document]
Comment (joshxg) [reply src/sync/incomingSyncUtils.js]: refactored masterListJoins to fix this.

File: src/sync/incomingSyncUtils.js (hunk 12 above)
Comment (joshxg) [reply src/sync/incomingSyncUtils.js]: Refactored to add a loop for each masterListJoin.
