### PR TITLE
#540 Parse as int, use set method, right align value

### LINKED ISSUE #540: Bugsnag: TransactionBatch.numberOfPacks must be of type: number
## Error in mSupply Mobile

**Error** in **index.android.bundle:733**
TransactionBatch.numberOfPacks must be of type: number

[View on Bugsnag](https://app.bugsnag.com/sustainable-solutions-nz-ltd/msupply-mobile/errors/59dd87b392bd570017522854?event_id=59dd87b392bd570017522853&i=gh&m=ci)

## Stacktrace

    index.android.bundle:733 - 

[View full stacktrace](https://app.bugsnag.com/sustainable-solutions-nz-ltd/msupply-mobile/errors/59dd87b392bd570017522854?event_id=59dd87b392bd570017522853&i=gh&m=ci)

*Created automatically via Bugsnag*

### PR DESCRIPTION
**Pull request by Chris-Petty**
~~Was meant to fix issue #540, but it doesn't really make sense. Doesn't seem to consistently throw the bug anymore, even if I switch back to master branch...~~

Fixes #540, I was testing with spacebar rather than backspace. Has to actually be an empty string for the bug to occur.

Changes are consistent with implementation elsewhere in app.

### CODE REVIEW

File: src/pages/SupplierInvoicePage.js [hunk 1]
```diff
@@ -88,7 +88,7 @@ export class SupplierInvoicePage extends React.Component {
     database.write(() => {
       switch (key) {
         case 'numberOfPacks':
-          transactionBatch.numberOfPacks = parsePositiveFloat(newValue);
+          transactionBatch.setTotalQuantity(database, parsePositiveInteger(newValue));
```
Comment (andreievg) [inline src/pages/SupplierInvoicePage.js]: If a the pack size field is re-introduced, this will be a gotcha (because of `his.numberOfPacks = this.packSize ? quantity / this.packSize : 0;` in `setTotalQuantity`. Also if there is a value in this field and invalid value is entered, the field will be set to 0... 
Would rather a simple 
```
const numberOfPacks = parsePositiveInteger(newValue);
if (numberOfPacks !== null) transactionBatch.numberOfPacks = numerOfPacks;
```

Comment (Chris-Petty) [reply src/pages/SupplierInvoicePage.js]: parsePositiveInteger will return 0 for all invalid inputs as of the next release of that module, so  that check will be redundant :). I can see that packsize may well sneak it's way back as a interface field, so sure.

Comment (andreievg) [reply src/pages/SupplierInvoicePage.js]: why would parsePositiveInteger return 0 ? This will override previous value of all inputs if invalid value is entered

Comment (andreievg) [reply src/pages/SupplierInvoicePage.js]: As per discussion in sussol-utils PR, sounds like parsePositiveInteger will be returning 0 even if value entered in invalid.. I am fine with this for now.

But can you make a comment in onEndEditing re the first part of my comment (i.e. if the pack size is re introduced we cannot use setTotalQuantity

Comment (Chris-Petty) [reply src/pages/SupplierInvoicePage.js]: Just realised to change the switch to 'quantity' rather than 'numberOfPacks'. The column is called Quantity, so I think this is clearer as it is now. If that the column actually represents number of packs, the header should say that too to be really clear in my opinion. Adding comment as suggested too.
